# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Lucas\Documents\GitHub\ShortProjects\Python\LoginApp\ConfirmRemove.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(302, 234)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(302, 234))
        MainWindow.setMaximumSize(QtCore.QSize(302, 234))
        MainWindow.setStyleSheet("background-color:lightgreen;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_nao = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_nao.setGeometry(QtCore.QRect(20, 170, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_nao.setFont(font)
        self.pushButton_nao.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_nao.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_nao.setStyleSheet("background-color:white; border: 2px solid green; border-radius: 9px;")
        self.pushButton_nao.setObjectName("pushButton_nao")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(20, 50, 261, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_nome.setFont(font)
        self.label_nome.setStyleSheet("color: RED;")
        self.label_nome.setText("")
        self.label_nome.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nome.setObjectName("label_nome")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(10, 10, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_titulo.setFont(font)
        self.label_titulo.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_titulo.setStyleSheet("color:green;")
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.pushButton_sim = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sim.setGeometry(QtCore.QRect(180, 170, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_sim.setFont(font)
        self.pushButton_sim.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_sim.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_sim.setStyleSheet("border: 2px solid green; border-radius: 9px;\n"
"background-color: rgb(255, 200, 200);")
        self.pushButton_sim.setObjectName("pushButton_sim")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_sim, self.pushButton_nao)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tela de Remoção"))
        self.pushButton_nao.setText(_translate("MainWindow", "NÃO"))
        self.label_titulo.setText(_translate("MainWindow", "Tem certeza de que deseja REMOVER o aluno"))
        self.pushButton_sim.setText(_translate("MainWindow", "SIM"))
