# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Lucas\Documents\GitHub\ShortProjects\Python\LoginApp\LoginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(406, 396)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(406, 396))
        MainWindow.setMaximumSize(QtCore.QSize(406, 396))
        MainWindow.setStyleSheet("background-color:lightgreen;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_login = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_login.setGeometry(QtCore.QRect(70, 70, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.lineEdit_login.setFont(font)
        self.lineEdit_login.setMouseTracking(True)
        self.lineEdit_login.setStyleSheet("background-color:white; border: 2px solid green; border-radius: 9px;")
        self.lineEdit_login.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_login.setPlaceholderText("Digite o login")
        self.lineEdit_login.setClearButtonEnabled(False)
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.lineEdit_senha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_senha.setGeometry(QtCore.QRect(70, 150, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.lineEdit_senha.setFont(font)
        self.lineEdit_senha.setMouseTracking(True)
        self.lineEdit_senha.setStyleSheet("background-color:white; border: 2px solid green; border-radius: 9px;")
        self.lineEdit_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_senha.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_senha.setClearButtonEnabled(False)
        self.lineEdit_senha.setObjectName("lineEdit_senha")
        self.pushButton_cadastre = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cadastre.setGeometry(QtCore.QRect(90, 280, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_cadastre.setFont(font)
        self.pushButton_cadastre.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_cadastre.setStyleSheet("background-color:white; border: 2px solid green; border-radius: 9px;")
        self.pushButton_cadastre.setObjectName("pushButton_cadastre")
        self.pushButton_login = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_login.setGeometry(QtCore.QRect(210, 280, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_login.setStyleSheet("background-color:white; border: 2px solid green; border-radius: 9px;")
        self.pushButton_login.setObjectName("pushButton_login")
        self.label_aviso = QtWidgets.QLabel(self.centralwidget)
        self.label_aviso.setGeometry(QtCore.QRect(70, 210, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_aviso.setFont(font)
        self.label_aviso.setStyleSheet("color: green;")
        self.label_aviso.setText("")
        self.label_aviso.setAlignment(QtCore.Qt.AlignCenter)
        self.label_aviso.setObjectName("label_aviso")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tela de Login"))
        self.lineEdit_senha.setPlaceholderText(_translate("MainWindow", "Digite a senha"))
        self.pushButton_cadastre.setText(_translate("MainWindow", "CADASTRE-SE"))
        self.pushButton_login.setText(_translate("MainWindow", "LOGIN"))
